@startuml
class shapes.DrawRectangle {
- State WaitForClick
- State Dragging
- Rectangle rect
- State state
~ void setState(State)
+ Rectangle getRectangle()
+ void mouseDown(Pos)
+ void mouseUp(Pos)
+ void mouseMove(Pos)
}
note left of shapes.DrawRectangle::rect
Setzen des Anfangsstates WaitForClick
end note

note left of shapes.DrawRectangle::setState(State)
Methoden der Klasse DrawRectangle
end note
note right of shapes.DrawRectangle::mouseDown(Pos)
Zuweisung der States mit der Oberklasse DrawRectangle
end note

abstract class shapes.DrawRectangle$State {
~ {abstract}void mouseUp(Pos)
~ {abstract}void mouseDown(Pos)
~ {abstract}void mouseMove(Pos)
}
note left of shapes.DrawRectangle$State::mouseUp(Pos)
Abstrakte Klasse State aus denen die States gemacht werden
end note



shapes.DrawRectangle +.. shapes.DrawRectangle$State
@enduml